name: trending_common
description: The interface and models for an API providing access to Trending.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.6.0
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  test: ^1.17.0
  very_good_analysis: ^5.0.0
